import { writeFile } from 'node:fs/promises'
import { getTournamentLockMetadata } from '../api/_lib/tournament-data.js'
import { normalizeOpenfootballData } from './tournament-normalize.js'

const OUTPUT_FILE = new URL('../api/_lib/tournament-static.ts', import.meta.url)

const tournament = await normalizeOpenfootballData()
const matches = tournament.matches.map(({ source: _source, ...match }) => match)
const payload = {
  groups: tournament.groups,
  teams: tournament.teams,
  matches,
  locks: getTournamentLockMetadata(matches),
  source: {
    ...tournament.source,
    fallback: true,
  },
}

const file = `import type { TournamentDataResponse } from './tournament-data.js'

// Generated by scripts/generate-tournament-static.ts from db/openfootball/worldcup-2026.json.
// Server-side fallback only. Client code must read /api/data/fixtures instead.
export const STATIC_TOURNAMENT_DATA = ${JSON.stringify(payload, null, 2)} satisfies TournamentDataResponse
`

await writeFile(OUTPUT_FILE, file)
console.log(`Generated ${OUTPUT_FILE.pathname}`)
